### PR TITLE
Remove Private Offer/Premium Packs

### PR DESCRIPTION
**Pull request by kgal-pan**
## Status
Ready

## Description
Remove references and mentions of Premium Packs/Private Offer.

### CODE REVIEW

**Comment by kgal-pan** [comment]
@tschanfeld - FYI.

**Comment by mchasepan** [comment]
Wait to merge this until @MMCrosby agrees.

**Comment by MMCrosby** [comment]
@kgal-pan The changes look good however we are on hold to move forward for the time being. I'll let you know when we can move forward with merging the changes. 
Thanks!

**Comment by kgal-pan** [comment]
Still waiting for confirmation.

**Comment by MMCrosby** [comment]
Waiting on confirmation from PM

**Comment by MMCrosby** [comment]
Waiting on confirmation from PM

**Review by MMCrosby — APPROVED** [review]
Looks great! Thank you!

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
