### PR TITLE
Update doc layout

### PR DESCRIPTION
**Pull request by sserrata**
* Upgrade docusaurus to alpha40
* Add support for docbar

### CODE REVIEW

**Comment by glicht** [comment]
Build is failing

**Comment by sserrata** [comment]
Build succeeded after clearing cache and retrying. I'm investigating why these transient build errors have been occurring. They are reproducible locally and appear to be cache related.

**Comment by sserrata** [comment]
The solution to the build errors was to pin all Docusaurus package versions in the `package.json` file. In addition to that, the Netlify build command was changed to `npm ci && npm run build` to ensure the pinned versions are always used for installation/deployment. 

We first noticed these build errors when the delta between the pinned and unpinned Docusaurus packages/plugins introduced incompatibilities. It should be noted that the build error side-effect has not been observed with `yarn`, which relies on the `yarn.lock` file, by default, to install. 

This pull-request is nearly ready for final review - just awaiting some contributions from @fvigo. 

Francesco, my suggestion is to fork the https://github.com/sserrata/content-docs repo and submit a PR to merge your changes into the `alpha40` branch.

**Comment by fvigo** [comment]
Thanks. @sserrata are you OK if we create a "devel" branch and merge this PR in, and then I will open my PR on the devel branch?

**Comment by sserrata** [comment]
Sure, that works. I don't have permissions to create new branches.

**Pull request merged**
