### PR TITLE
Update development-partners.md

### PR DESCRIPTION
**Pull request by mchasepan**
add image tag to docusaurus so it shows in posts and linkedIn as generic XSOAR and not any one specific partner logo.
Not sure how to test this, @ShahafBenYakir @sserrata ?

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by mchasepan** [comment]
Ah, okay that seems to work. It doesn't show the new image, but doesn't show the QMasters Image. Maybe an svg file isnt supported @sserrata ?

Old page:
image

New page:
image

**Comment by sserrata** [comment]
I think support for SVG may vary by site you're posting to. Can you switch to PNG or JPG to be safe?

**Comment by mchasepan** [comment]
Hmm. Nope, that doesnt seem to work either. Created a png, updated the md and upload the file. Can you check if i did it right @sserrata  thanks. 
image

**Comment by sserrata** [comment]
Hi @mchasepan, your `image` tag is referencing a PNG file that hasn't been pushed to production yet. (the link below currently results in a `404`)

https://xsoar.pan.dev/img/Cortex_XSoar_logos_RGB_Cortex-Ng-Soar-Horizontal_250_white.png

It should work once it's merged.

**Comment by mchasepan** [comment]
> It should work once it's merged.
DUH. Thanks @sserrata

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
