### PR TITLE
Email Communication Content Pack documentation update

### PR DESCRIPTION
**Pull request by mikejrizzo**
## Status
In Hold (These updates must be merged at the same time as Email Communication pack updates pending in https://github.com/demisto/content/pull/17717)

## Related Issues
No issues

## Description
I have submitted a pull request with additional functionality in https://github.com/demisto/content/pull/17717. This documentation update describes the updated features and how to configure and use them.  I have added new screenshot images to this branch and deleted images that are outdated and no longer needed for this document.

## Screenshots
n/a

### CODE REVIEW

**Comment by julieschwartz18** [comment]
Doc review complete for the Email-Communication-Readme.md file. @mikejrizzo - please review and confirm it looks ok. In addition, please note the following images are not viewable (when going to the link there is a 404 error):
- Layout
- EmailCommunication_PopUp
- EmailCommunication_SendEmailReplySettings

**Comment by mikejrizzo** [comment]
@julieschwartz18 Thanks for reviewing my changes!  Your edits all look good to me.

The images you're getting 404's for are new files that I'm including with this pull request.  The URLs I used in the document should reference the final location of these new files once they're merged.  If there's a better way to make new images visible during the review process please let me know and I'll use that method next time.

**Comment by mikejrizzo** [comment]
Adding a comment to refresh activity - this PR isn't stale, just waiting on https://github.com/demisto/content/pull/17717.

**Comment by mikejrizzo** [comment]
@julieschwartz18 @yuvalbenshalom This PR got closed as stale since we're still waiting on the other PR for the code updates this document update is about.  Are you able to re-open this same PR, or do I need to open another one for the same documentation update?

**Review by yuvalbenshalom — APPROVED** [review]

**Pull request merged**
