### PR TITLE
Updated web site with several changes

### PR DESCRIPTION
**Pull request by fvigo**
- Reviewed sidebars and created sub-categories
- Added use cases and Design best practices pages
- Pointing to the Demisto Blog
- Reviewed why-demisto
- Reviewed become-a-partner
- Removed architecture docs
- Added information for non-partners in the main page
- Removed video from Main Page
- Several minor changes (check commit log)

### CODE REVIEW

**Comment by glicht** [comment]
I am getting an overflow on `Become a Technology Partner` in the header:

image

**Comment by fvigo** [comment]
> I am getting an overflow on `Become a Technology Partner` in the header:
> 
> image

@sserrata  @csestito  could you please have a look? It displays correctly on my end also on a smaller screen. I'm using Chrome 78. Thanks!

**Comment by glicht** [comment]
Still getting the overflow:

image

**Comment by fvigo** [comment]
> Still getting the overflow:
> 
> image

Overflow should be fixed now

**Comment by fvigo** [comment]
hey @glicht please review at your convenience, the layout should be OK now

**Pull request merged**
