### PR TITLE
PS-Remote Article

### PR DESCRIPTION
**Pull request by David-BMS**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/32168
## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by David-BMS** [comment]
@kirbles19 Please notice there are 2 articles.

**Comment by ShirleyDenkberg** [comment]
@michalgold Doc review completed.

**Review by michalgold — APPROVED** [review]

**Comment by glicht** [comment]
@David-BMS can we merge?

**Comment by David-BMS** [comment]
@glicht The article is for the pack itself which isnt merged yet
Best merge them at the same time

**Comment by David-BMS** [comment]
Pending merge of
https://github.com/demisto/content/pull/10826

**Comment by David-BMS** [comment]
Pending merge of
demisto/content#10826

**Comment by glicht** [comment]
@David-BMS status?

**Comment by David-BMS** [comment]
@glicht again pending the PR for the integration
hopefully will be completed early June

**Comment by David-BMS** [comment]
Should be merged next week

**Pull request merged**
