### PR TITLE
Restyle hamburger menu

### PR DESCRIPTION
**Pull request by sserrata**
## Status
Ready

## Related Issues
fixes: link to the issue

## Description
Introduces some minor UX/UI tweaks to mobile sidebar button:

* restyle mobile sidebar button
* change marketplace mobile sidebar button from hamburger to filter icon

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by sserrata** [comment]
Please hold on merging until additional style fixes are added

**Comment by sserrata** [comment]
Mobile marketplace sidebar button icon not showing on iOS. Works in Chrome mobile emulator. Tweaking CSS to see if the problem is introduced after webpack bundles styles.

IMG_306E71EC8E7E-1

**Comment by sserrata** [comment]
@reutshal This PR is not ready for review. The mobile sidebar button icon issue was resolved:

IMG_9974B5FE7CC1-1

**Review by reutshal — APPROVED** [review]

**Review by reutshal — CHANGES_REQUESTED** [review]
Please merge from master, the rainbow bar is still here

**Review by reutshal — APPROVED** [review]

**Pull request merged**
