### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tschanfeld**
PreProcessingRule
replacing current image here- https://xsoar.pan.dev/docs/incidents/incident-pre-processing#example as it doesn't match the text

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by tschanfeld** [comment]
@Itay4 Kobbi doesn't have permissions to approve this. Can you?

**Review by Itay4 — APPROVED** [review]
shouldnt we also change the subject text?

**Comment by tschanfeld** [comment]
From [potential phishing]? What do you suggest?

**Comment by Itay4** [comment]
the text says: `Therefore, we created, a condition for incoming incidents that have a subject line that contains the text, this is a phishing email.`

**Comment by kgal-pan** [comment]
@tschanfeld - In continuation to @Itay4's comment and the comments in the [issue](https://github.com/demisto/etc/issues/40379), I reviewed the page on the preview site and found a few things that still need to be modified:

- The first paragraph:

>In most cases, in a phishing campaign, the email subject will be similar. Therefore, we created, a condition for incoming incidents that have a subject line that contains the text, this is a phishing email.

In the image, the `Email Subject` field is compared to `[potential phishing]` while in the line above, it mentions that it compares it to 'this is a phishing email':

>subject line that contains the text, this is a phishing email

We need to change the line above to match the image, i.e.:

>subject line that contains the text '[potential phishing]'

- The second paragraph:

> As we know that this is a campaign, we are going to ask to close the incoming incident and link it to an already existing incident.

The image is showing a `Drop and update` action while the second sentence in the paragraph above mentions:

>we are going to ask to close the incoming incident and link it to an already existing incident

We need to change the second sentence to match the actual action, `Drop and update`.

Let me know if you have any questions.

**Comment by tschanfeld** [comment]
@Itay4  created new pull request with new image version

**Comment by tschanfeld** [comment]
@kgal-pan The image was changed from drop and update to link and close, so the text should be correct. Does it make sense this way, in terms of the use case?

**Pull request closed without merging**
