### PR TITLE
Content repo docs

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Description
Generate reference docs from the content repository.

* Added a new npm task: `reference-docs` which generates the docs.
* Added `npm test` which run the pytest tests to check the generating script

For the content docs we support both html docs and MD docs (most are currently html). For html they are rendered as is. 

Example of MD based documentation: https://deploy-preview-33--demisto-content-docs.netlify.com/docs/reference/integrations/domain-tools-iris

Todo:
* Review docs

This is still in progress. Will update this comment once ready.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by glicht** [comment]
@kirbles19 use the following preview lint to review: https://deploy-preview-33--demisto-content-docs.netlify.com/docs/reference/index

**Comment by fvigo** [comment]
@glicht what is missing for this to be added to the Reference section?

**Comment by glicht** [comment]
@anara123 @fvigo ready. See preview site.

**Comment by fvigo** [comment]
Why are the following files in the `content-repo` directory needed?

- error-1.txt
- error-2.txt
- error.txt
- error2.txt
- pipenv.out

**Comment by glicht** [comment]
removed the error and out file (it was left over)

**Pull request merged**
