### PR TITLE
Microsoft auth guide

### PR DESCRIPTION
**Pull request by Itay4**
## Status
Ready

## Description
a generic guide for microsoft auth to explain about the 2 auth options

every microsoft integration doc should refer to it once published

### CODE REVIEW

**Comment by Itay4** [comment]
@kirbles19 please review

**Comment by glicht** [comment]
@kirbles19 preview available here: https://deploy-preview-190--demisto-content-docs.netlify.app/docs/reference/articles/microsoft-integrations---authentication

**Comment by kirbles19** [comment]
@Itay4 Done.

**Comment by Itay4** [comment]
@glicht can you please approve?

**Pull request merged**
