### PR TITLE
Update become-a-tech-partner - training links.md

### PR DESCRIPTION
**Pull request by marcellarichmond**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Review by mchasepan — APPROVED** [review]

**Comment by mchasepan** [comment]
@ShahafBenYakir why did this build fail? Looks okay to me. Thx.

**Comment by ShahafBenYakir** [comment]
Can you re-run? I think this was solved

**Comment by mchasepan** [comment]
@ShahafBenYakir reran and failed again. And Guy just asked about it. 
Can you please address and merge?

**Comment by ShahafBenYakir** [comment]
Have you pulled from master?

**Comment by mchasepan** [comment]
Closing, opened branch PR via https://github.com/demisto/content-docs/pull/793

**Pull request closed without merging**
