### PR TITLE
[Dev-task] xsoar.pan.dev - Add links from reference docs to their corresponding packs pages in marketplace 

### PR DESCRIPTION
**Pull request by daryakoval**
## Status
In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/39492

## Description
We want to add links from the entities' reference docs to their corresponding pack page in the marketplace.

### CODE REVIEW

**Comment by daryakoval** [comment]
### Examples:
---
image
---
image
---
image
---
image
---
image

**Review by dantavori — CHANGES_REQUESTED** [review]
nice 👑

**Comment by daryakoval** [comment]
## Changed added line to be a title, what do you think? @dantavori 

image
---
image
---
image
---
image

**Review by dantavori — COMMENTED** [review]
let's make sure that we have links also for private packs as well - see [example](https://pull-request-756--demisto-content-docs.netlify.app/docs/reference/playbooks/iam---sync-user) in the current preview.
if you can't get the pack name from the metadata for private packs, the pack dir name will be enough - you can accomplish that with try-except in the get_packname_from_metadata function.

**Pull request merged**
