### PR TITLE
add "Deprecated" callout to content from Packs/DeprecatedContent

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Related Issues
fixes: link to the issue

## Description
Any content in DeprecatedContent will get a "Deprecated" callout. Mostly relevant for playbooks that don't have the yml setting of deprecated.

## Screenshots
image

### CODE REVIEW

**Comment by glicht** [comment]
@michalgold fyi

**Comment by anara123** [comment]
@glicht in playbooks there is `hidden` boolean. We can use that field to identify deprecated playbooks

**Comment by glicht** [comment]
> @glicht in playbooks there is `hidden` boolean. We can use that field to identify deprecated playbooks

Will add it too. Although, from what I see we barely use it.

**Comment by anara123** [comment]
We started using it lately

**Comment by glicht** [comment]
@anara123 hidden is also checked. You can see an example here: https://deploy-preview-207--demisto-content-docs.netlify.app/docs/reference/playbooks/q-radar---get-offense-correlations-

**Pull request merged**
