### PR TITLE
Replace screenshots

### PR DESCRIPTION
**Pull request by ShirleyDenkberg**
aws-feed-configuration-4
aws-feed-configuration-5
aws-feed-configuration-1
aws-feed-configuration-2
aws-feed-configuration-3

## Status
Ready

## Description
Need new screenshots of the AWS Feed instance in the Migrating MineMeld to Cortex XSOAR file https://github.com/demisto/content-docs/edit/master/docs/tutorials/tut-minemeld-migration.md). 
The Sub-Feeds field is now called Services. This is correctly documented in the text. Just the screenshots need to be replaced.

 There are 5 versions of the same screenshot that need to be replaced in the file.

## Screenshots
aws-feed-configuration-5
aws-feed-configuration-1

aws-feed-configuration-4

aws-feed-configuration-2
aws-feed-configuration-3

### CODE REVIEW

**Comment by glicht** [comment]
For some reason the images came out very big. Please take a look at the preview site:

https://deploy-preview-116--demisto-content-docs.netlify.app/docs/tutorials/tut-minemeld-migration

**Comment by avidan-H** [comment]
@ShirleyDenkberg as @glicht mentioned the images you've added are quite large. If you're on a mac, you can open the images in the `Preview` application and resave them after resizing the images as shown in the screenshot below. 

Once you've done that, you can reupload the resized images here. For reference, the size of one of the images you are replacing is 414 x 662 pixels.


image

**Comment by glicht** [comment]
@ShirleyDenkberg do you want to merge?

**Comment by ShirleyDenkberg** [comment]
@glicht Yes.  I looked it over.  It looks good.  Please merge.

**Pull request merged**
