### PR TITLE
Create Endpoint_Malware_Investigation_-_Generic_V2.md

### PR DESCRIPTION
**Pull request by evisochek**
## Status
In Progress

## Description

This article will provide guidelines for Endpoint Malware Investigation - Generic V2 playbook  

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by ShirleyDenkberg** [comment]
@evisochek Doc review completed.

**Comment by fvigo** [comment]
@ShahafBenYakir @kirbles19 who should approve/merge these PR on GitHub once they get the "docs approved"?

**Comment by ShahafBenYakir** [comment]
@evisochek I can't seem to find this playbook in content repo is it there? why aren't we adding this README through the content repo?

**Comment by evisochek** [comment]
This PB is the new version to "Endpoint_Malware_Investigation_-_Generic" due to the implementation of indicators extraction rules for 6.2 version.
@ShahafBenYakir

**Pull request closed without merging**
