### PR TITLE
Code conventions

### PR DESCRIPTION
**Pull request by Itay4**
## Status
In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/26305

## Description
Modifying code conventions article, and adding pwsh examples to it using tabs

### CODE REVIEW

**Comment by fvigo** [comment]
@Itay4 is this PR still valid? shall we review and merge it?

**Comment by Itay4** [comment]
@fvigo didnt get to continue here, wanted to add more pwsh conventions
we can close it for now if you prefer, and ill reopen when i get some time

**Comment by fvigo** [comment]
No worries, we can keep it open

**Comment by anara123** [comment]
closing for now. Reopen when you continue working on it

**Pull request closed without merging**
