### PR TITLE
Update Docusaurus to Alpha 58

### PR DESCRIPTION
**Pull request by csestito**
## Status
In Hold for verification

## Related Issues
upgrading Docusaurus to Alpha 58

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by csestito** [comment]
@sserrata could you please review?

**Comment by sserrata** [comment]
Looks good. Only one small issue I noticed: the XSOAR logo crowds out the Algolia search input in mobile view. Not sure that there's much we can do.

Screen Shot 2020-07-23 at 11 11 32 AM

**Comment by sserrata** [comment]
One possible solution to the logo search bar problem:

```
@media (max-width: 380px) {
  .navbar__logo {
    width: auto !important;
  }
}
```

**Comment by sserrata** [comment]
> Looks good.
> 
> Did you take a look at the following comment from GuardRails: [#220 (comment)](https://github.com/demisto/content-docs/pull/220#issuecomment-662084831) ?

@glicht I looked into this vulnerability and, in this context, it appears to be benign. The HTML is derived from Docusaurus which means it can be trusted.

I tested using DOMPurify to sanitize the HTML but it wasn't enough for Guardrails not to report the vulnerability. Guardrails appears to simply report on the use of `dangerouslySetInnerHTML` and doesn't factory in additional steps to sanitize the HTML.

**Comment by csestito** [comment]
Concurred @sserrata. Was going to bring this up with the docusaurus team, but it looks to be safe here. Going to meet with netlify today to discuss the memory and time issues that are happening with the build before I push this through.

**Comment by glicht** [comment]
@csestito I've added a .npmrc file that increasing the node available memory to 5GB. Seems to have solved the build failure.

**Comment by csestito** [comment]
@glicht Thanks for the help, feel free to merge.

**Pull request merged**
