### PR TITLE
Add article on digital forensics content in XSOAR

### PR DESCRIPTION
**Pull request by ali-sawyer**
## Status
Ready

## Related Issues
N/A

## Description
For digital forensic investigators interested in using XSOAR, centralize list of XSOAR content that support digital forensics so it is easy to find in one place.

Please review and reach out me to with any questions/feedback. (I am a PANW employee.)

## Screenshots
N/A

### CODE REVIEW

**Comment by ShirleyDenkberg** [comment]
@MariaBord @GuyAfik Doc review completed.

**Comment by GuyAfik** [comment]
@ali-sawyer can you please take a look about the failed build?

**Comment by ali-sawyer** [comment]
@GuyAfik @ShirleyDenkberg got it finally! Just needs an approval.

**Review by GuyAfik — APPROVED** [review]
looks great, @ali-sawyer thank you for adding this!

**Pull request merged**
