### PR TITLE
improvements to welcome page

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Related Issues
fixes: link to the issue

## Description
Welcome page had some empty sections. Removed empty sections and trimmed it down.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by glicht** [comment]
@kirbles19 would appreciate your help on this page

**Comment by mchasepan** [comment]
I added many of my changes from #175 into this one.

**Comment by glicht** [comment]
@kirbles19 waiting on you. You can see a preview here: https://deploy-preview-173--demisto-content-docs.netlify.app/docs/welcome

**Comment by kirbles19** [comment]
Looks good, a few updates.

**Pull request merged**
