### PR TITLE
cla updates

### PR DESCRIPTION
**Pull request by ShahafBenYakir**
## Status
Ready

## Description
Added FAQ on CLA

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
@mchasepan What do you think?

**Review by mchasepan — APPROVED** [review]
A few small changes, looks good

**Comment by ShahafBenYakir** [comment]
Thanks. Merging.

**Comment by ShahafBenYakir** [comment]
FYI @fvigo need to make sure we include this into your changes to FAQ.

**Pull request merged**
