### PR TITLE
Update playbooks-extend_context.md

### PR DESCRIPTION
**Pull request by ali-sawyer**
Add example of extend-context for `SearchIncidentsV2`.

## Status
Ready

## Related Issues
N/A

## Description
Provide another useful extend-context example.

## Screenshots
N/A

### CODE REVIEW

**Comment by ali-sawyer** [comment]
@tschanfeld could you please take a look so we can get this merged into the docs? Thanks!

**Comment by ShirleyDenkberg** [comment]
@ali-sawyer Doc review completed.

**Comment by ali-sawyer** [comment]
Thanks @ShirleyDenkberg, could you hit Approve on the review? It is still showing that merging this PR is blocked, at least for me.

**Comment by ali-sawyer** [comment]
Updated. Ok, who can we loop in to approve this PR?

**Review by MosheEichler — APPROVED** [review]

**Review by MosheEichler — APPROVED** [review]

**Pull request merged**
