### PR TITLE
Update playbook-settings.md

### PR DESCRIPTION
**Pull request by tschanfeld**
changed details of quiet mode, per notes from Meir

## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by tschanfeld** [comment]
@meirwah

**Comment by revahh** [comment]
@meirwah looks good.
the only thing i'm not sure is about auto-extract. 
@itayronen quiet-mode is impact on auto extract?

**Comment by itayronen** [comment]
> @meirwah looks good.
> the only thing i'm not sure is about auto-extract.
> @itayronen quiet-mode is impact on auto extract?

Never tested until now.
Tested on a task that prints an indicator, and on a task that explicitly calls `extractIndicators`.
Both tasks did on quiet mode, did NOT create any indicators on the incident.

**Comment by tschanfeld** [comment]
This pull request has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs.

**Comment by tschanfeld** [comment]
@meirwah

**Comment by tschanfeld** [comment]
can someone squash/merge? i'm not supposed to. 

This pull request has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs.

**Comment by glicht** [comment]
> can someone squash/merge? i'm not supposed to.
> 
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs.

@tschanfeld I will merge. But in general you can feel free to "Squash and merge" once a PR is approved and it is ready to be merged.

**Pull request merged**
