### PR TITLE
Upgrade alpha70

### PR DESCRIPTION
**Pull request by sserrata**
## Status
In Progress

## Related Issues
fixes: link to the issue

## Description
Upgrades to Docusaurus alpha 70. 

Please note that this release checks for non-empty markdown link and image URLs. There were three reference docs flagged during my testing that contained empty image URLs:

- /docs/reference/playbooks/get-file-sample-from-hash---generic.md
- /docs.reference/playbooks/playbook1.md
- /docs.reference/playbooks/playbook2.md

Not addressing empty markdown link or image URLs can result in the following error:

`Error: Markdown image url is mandatory` or `Error: Markdown link url is mandatory`

## Screenshots
Paste here any images that will help the reviewer

### CODE REVIEW

**Comment by sserrata** [comment]
@glicht Can you assist with the most recent build error? It appears to be related to a missing python package.

```python
Traceback (most recent call last):
  File "./gen_pydocs.py", line 8, in <module>
    import docspec
  File "/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q/lib/python3.8/site-packages/docspec/__init__.py", line 44, in <module>
    from nr.databind.json import JsonModule
ModuleNotFoundError: No module named 'nr.databind.json'
```

**Comment by glicht** [comment]
> @glicht Can you assist with the most recent build error? It appears to be related to a missing python package.
> 
> ```python
> Traceback (most recent call last):
>   File "./gen_pydocs.py", line 8, in <module>
>     import docspec
>   File "/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q/lib/python3.8/site-packages/docspec/__init__.py", line 44, in <module>
>     from nr.databind.json import JsonModule
> ModuleNotFoundError: No module named 'nr.databind.json'
> ```

Will check. Started a re-build as a start. It might be some temporary install issue of python deps.

**Comment by glicht** [comment]
@sserrata re-build passed. Are you ok to merge?

**Review by glicht — APPROVED** [review]

**Comment by glicht** [comment]
@sserrata note that we got one new alert from lgtm. See: https://github.com/demisto/content-docs/pull/429#issuecomment-771068336

**Comment by sserrata** [comment]
Everything looks good to me. I'm ready to merge.

**Pull request merged**
