### PR TITLE
Shift management- pack documentation

### PR DESCRIPTION
**Pull request by evisochek**
## Status
In Progress

## Related Issues
https://github.com/demisto/etc/issues/28569

## Description
Shift management and shift handover are crucial processes of SOC team management.
This pack's purpose is Provide a single interface for all those essential elements in one place in order to prevent loss of data in the shift handover process.

### CODE REVIEW

**Comment by kirbles19** [comment]
@evisochek Can you please rename this PR to indicate it's for pack documentation.

**Comment by kirbles19** [comment]
@ShirleyDenkberg this is related to https://github.com/demisto/content/pull/10750

**Comment by ShirleyDenkberg** [comment]
@evisochek Please review the content carefully.  All links will need to be checked when the automations and playbooks are uploaded. We need a link to a good layout.

**Review by michalgold — APPROVED** [review]
Approving as per @evisochek's earlier conversation with @ShirleyDenkberg. No further changes were eventually made.

**Pull request merged**
