### PR TITLE
chore: Test Docusaurus webpack 5 support

### PR DESCRIPTION
**Pull request by slorber**
Use an unreleased version of Docusaurus to test the webpack5 support works for this site.

See also https://github.com/facebook/docusaurus/pull/4089

It might improve performances on rebuild, but it requires that you set up caching of `node_modules/.cache` across your CI builds (not sure how this site is built exactly)

Running locally:
- First build: 1700s
- Second build: 350s

### CODE REVIEW

**Comment by sserrata** [comment]
Hi @slorber, thanks for helping to test the performance benefits of webpack 5 with our site!

FYI, @glicht discovered we could shave ~12 minutes off the server build time by wrapping the `DocSidebar` component in `BrowserOnly`.  See https://github.com/demisto/content-docs/blob/master/src/theme/DocSidebar/index.js#L7 for details. It's a small tweak with considerable benefits for large sites.

**Comment by sserrata** [comment]
Concerning `ValidationError: "custom_edit_url" is not allowed to be empty`, I believe we are using empty strings (`""`) to hide the edit link on some docs. Could that be what's causing this error? If so, is there another way we can disable the edit URL/link?

**Comment by slorber** [comment]
> Hi @slorber, thanks for helping to test the performance benefits of webpack 5 with our site!

NP, I'd be happy to help improve the perf of this site as it's probably one of the largest Docusaurus site and a good benchmark showing that we should rather improve 😅 !

> FYI, @glicht discovered we could shave ~12 minutes off the server build time by wrapping the DocSidebar component in BrowserOnly. See https://github.com/demisto/content-docs/blob/master/src/theme/DocSidebar/index.js#L7 for details. It's a small tweak with considerable benefits for large sites.

Thanks, I think it makes sense that Docusaurus could only render collapsed sidebar items on the client, after hydration already happened. Didn't think the sidebar could have a significant impact on build time, but it makes sense for very large sidebars like yours. Will note to investigate that, but I'm not sure it's a good idea as it can have impacts on SEO, as crawlers could have a harder time finding links of your site.

> ValidationError: "custom_edit_url" is not allowed to be empty

This is a new frontmatter validation we added recently, but will relax it to make it allow empty strings as before.

--- 

BTW, unrelated but can you add your apps to the Docusaurus showcase, please? 
https://docusaurus.io/showcase

**Comment by glicht** [comment]
@slorber we can add caching of `node_modules/.cache` but it will be a cache that is refreshed based on a time period. For example refresh the cache once every X weeks. I think it should provide value as most of our pages don't change too often.

**Comment by glicht** [comment]
@slorber also wanted to say thanks on this effort. Really appreciated. 

I am looking at the build log and I see that the build is failing on an empty value for `custom_edit_url`. I think this is a change in how docusaurus treats this front matter property.

**Comment by slorber** [comment]
> @slorber we can add caching of node_modules/.cache but it will be a cache that is refreshed based on a time period. For example refresh the cache once every X weeks. I think it should provide value as most of our pages don't change too often.

I don't think it's a problem if once  every X weeks you have a full rebuild with a cold cache. You'll only get the speed improvements if the cache is persisted, which is still better than the current state.

> @slorber also wanted to say thanks on this effort. Really appreciated.

no problem :) helping you will help the whole Docusaurus community in the end

> I am looking at the build log and I see that the build is failing on an empty value for custom_edit_url. I think this is a change in how docusaurus treats this front matter property.

Yes definitively, I'll fix this and update the PR. Was able to build by doing some local doc changes.

**Comment by slorber** [comment]
Noticed on your doc that you have both a markdown title + a frontmatter title:

```md
---
id: 19.10.0
title: "19.10.0"
custom_edit_url: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/releases/19.10.0.md
hide_title: true
---

# Demisto Content Release Notes for version 19.10.0 (30654)
##### Published on 02 October 2019
### Integrations

```

Can you explain the motivation?

My intuition is that you want the page title to be the frontmatter.title, and the markdown title to be the user-visible h1 heading. I'm restoring this behavior that changed recently in https://github.com/facebook/docusaurus/issues/4665#issuecomment-825831367
But I find this behavior a bit implicit and not really defined/documented, so if you can explain me your use-case + ideal API to achieve it I'd be happy to ear it.


Also, there's the `hide_title: true` being used, probably to avoid a duplicate h1 title issues we previously had.
Since alpha 73 you should remove it because it will prevent any heading (from BOTH md or frontmatter) to appear at the top of your doc, so it will really hide the title:

image

**Comment by slorber** [comment]
Upgraded the PR to latest but had some issues:
- index.json for marketplace is missing  (not sure how to generate it)
- query-string package is not in package.json

Also suggesting to remove the `hide_title` frontmatter as the release pages don't have titles anymore:

image


It's probably worth it to "re-swizzle" your custom theme comps at some point to upgrade them, as some code has changed and you might want to sync with our upstream changes

**Comment by sserrata** [comment]
> Upgraded the PR to latest repo changes but had some issues:
> 
> * index.json for marketplace is missing  (not sure how to generate it)
> * query-string package is not in package.json
> 

The command `npm run marketplace-docs` will generate the `index.json` needed for marketplace. As for `query-string`, it appears to work even without it being explicitly installed/included in `package.json`. Could it be built-in?

**Comment by slorber** [comment]
Can you please approve the CI workflow. This is a new thing required now, to protect against hackers using CI to farm bitcoins 😅

**Comment by slorber** [comment]
fixed a little breaking change in Docusaurus code in the marketplace sidebar code.

this PR is ready for review now

**Comment by Itay4** [comment]
> Can you please approve the CI workflow. This is a new thing required now, to protect against hackers using CI to farm bitcoins 😅

approved

**Comment by slorber** [comment]
Hi

Please let me know if you find any issues with this PR, as I'm trying to see if the released Webpack 5 support is good ;)

**Comment by glicht** [comment]
> Noticed on your doc that you have both a markdown title + a frontmatter title:
> 
> ```lisp
> ---
> id: 19.10.0
> title: "19.10.0"
> custom_edit_url: https://github.com/demisto/content-docs/blob/master/content-repo/extra-docs/releases/19.10.0.md
> hide_title: true
> ---
> 
> # Demisto Content Release Notes for version 19.10.0 (30654)
> ##### Published on 02 October 2019
> ### Integrations
> ```
> 
> Can you explain the motivation?
> 
> My intuition is that you want the page title to be the frontmatter.title, and the markdown title to be the user-visible h1 heading. I'm restoring this behavior that changed recently in [facebook/docusaurus#4665 (comment)](https://github.com/facebook/docusaurus/issues/4665#issuecomment-825831367)
> But I find this behavior a bit implicit and not really defined/documented, so if you can explain me your use-case + ideal API to achieve it I'd be happy to ear it.
> 
> Also, there's the `hide_title: true` being used, probably to avoid a duplicate h1 title issues we previously had.
> Since alpha 73 you should remove it because it will prevent any heading (from BOTH md or frontmatter) to appear at the top of your doc, so it will really hide the title:
> 
> image

Hi @slorber sorry for the late response. Our motivation is basically to have a different h1 title on the page than the one used in the sidebar. See the example image:

image

Will this be possible with the upcoming Docusaurus update?

**Comment by glicht** [comment]
@slorber thanks for the clarification. When we go and update we will change the frontmatter.

I am going to try to also enable the caching on this PR to see the effect. Will be committing directly to your branch.

**Comment by slorber** [comment]
Thanks, let me know how it works.

About the large sidebar, I've opened an issue to track potential perf improvements: https://github.com/facebook/docusaurus/issues/4753

I will also try to figure out how to improve the developer experience, because running `docusaurus start` on your site is quite painful atm right?

**Comment by slorber** [comment]
@glicht FYI we also added a way to use esbuild in the beta.0 , maybe you can try it and see how it improves perf?

It's not yet documented, but we are using it in production on the Docusaurus site itself.

https://github.com/facebook/docusaurus/blob/master/website/docusaurus.config.js#L66

https://github.com/facebook/docusaurus/issues/4765#issuecomment-841135926

**Comment by glicht** [comment]
Thanks @slorber. We are planning to upgrade soon. Will check this out.

**Comment by slorber** [comment]
> FYI, @glicht discovered we could shave ~12 minutes off the server build time by wrapping the DocSidebar component in BrowserOnly. See https://github.com/demisto/content-docs/blob/master/src/theme/DocSidebar/index.js#L7 for details. It's a small tweak with considerable benefits for large sites.

@sserrata @glicht this Docusaurus PR might make your "sidebar only on the client" less necessary:
https://github.com/facebook/docusaurus/pull/5136

It won't save as much time as simply not rendering the whole sidebar on the server, but seems to me a good compromise. It's up to you to keep your existing optim if you want.

**Pull request closed without merging**
