### PR TITLE
Add demisto.results section and update return_outputs section

### PR DESCRIPTION
**Pull request by avidan-H**
## Status
Ready

## Related Issues
fixes: https://github.com/demisto/content/pull/5405#pullrequestreview-340619400
related: https://github.com/demisto/content/pull/5405
related: https://github.com/demisto/content/pull/5404

## Description
Document the new entry field `IndicatorTimeline` (and soon-to-be updated `return_outputs`).

### CODE REVIEW

**Comment by fvigo** [comment]
This is great and was needed! 

Question: shall we create a new document for this, and add a reference in Code Conventions to it? I think Code Conventions is too big, we should split it in smaller chunks, keeping it more as an index. What do you think @glicht  @anara123  ?

**Comment by anara123** [comment]
in the code conventions we should mention that as a convention they should use return_outputs and have a link to other page of references where we have all the built in commands

**Comment by avidan-H** [comment]
@anara123 The references page documentation is as-of-yet undeveloped so I don't see that there is anything to link to right now. I will note that using `return_outputs` is the preferred method of returning entries to the war room and that `demisto.results()` should only be used if the user's use-case demands more specificity than `return_outputs` allows.

**Comment by avidan-H** [comment]
@glicht is there any other information about `IndicatorTimeline` that you want to be included, or is what I wrote enough?

**Comment by glicht** [comment]
@avidan-H please add information regarding when a timeline object should be included with an example (provide link to an integration that actually does this).

**Comment by avidan-H** [comment]
@glicht awaiting review.

**Comment by glicht** [comment]
Add that timeline can also be used in a script

**Pull request merged**
