### PR TITLE
insert approved usecases and docs to pack docs article

### PR DESCRIPTION
**Pull request by Itay4**
## Status
Ready

## Description
- reading approved usecases and tags list and adding them to the pack docs article
- improved indentation formatting for pack categories optional values

## Screenshots
image

image

### CODE REVIEW

**Comment by glicht** [comment]
@Itay4 see my commit where I formatted Categories. Let's use bullets and not new lines for tags and use-cases.

**Comment by Itay4** [comment]
@glicht i think it was over indented with your latest commit
i suggest dedent a bit as `Analytics & SIEM ` is in the following screenshot:
image

**Comment by glicht** [comment]
> @glicht i think it is a bit over indented in your latest commit
> i suggest אם dedent as `Analytics & SIEM ` is in the following screenshot:
> image

Formatting this `details` block turns out to be non trivial. I'll see if I can improve it.

**Comment by glicht** [comment]
@Itay4 I think the formatting is good now. Let's use the same for tags and use-cases:

image

**Comment by Itay4** [comment]
@glicht done and also formatted the core packs list

**Review by glicht — APPROVED** [review]

**Pull request merged**
